# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=50)),
                ('userName', models.CharField(blank=True, default='', max_length=50)),
                ('shopName', models.CharField(max_length=50)),
                ('foodName', models.CharField(max_length=50)),
                ('meal', models.CharField(choices=[('早餐', '早餐'), ('早午餐', '早午餐'), ('午餐', '午餐'), ('下午茶', '下午茶'), ('晚餐', '晚餐'), ('宵夜', '宵夜')], max_length=10)),
                ('type', models.CharField(choices=[('台式', '台式'), ('中式', '中式'), ('西式', '西式'), ('泰式', '泰式'), ('義式', '義式'), ('日式', '日式'), ('韓式', '韓式'), ('法式', '法式'), ('越南', '越南'), ('印度', '印度'), ('其它', '其它')], max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('message', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='register.User')),
            ],
        ),
    ]
